@startuml
left to right direction
:Bruker: as Bruker
:Lokallag: as Lokal
:Arrangører: as Arrangører
:Sponsorer: as Sponsorer
:3-parter: as Tredje
:Admin: as Admin

(Registrere aktivitet) as (RegAktivitet)
(Påmelding) as (Påmelding)
(Opprette brukerprofil) as (Opprette)
(Opprette ny konkurranse) as (NyKonk)
(Browse konkurranser) as (Browse)



Bruker -> (Opprette)
Bruker --> (Browse)
Bruker --> (Påmelding)

Admin --> (NyKonk)

Lokal --> (Opprette)
Lokal --> (Browse)
Lokal --> (Påmelding)
Lokal --> (RegAktivitet)
Lokal --> (NyKonk)

Arrangører --> (Opprette)



@enduml
