@startuml
left to right direction
:Bruker: as Bruker
:Lokallag: as Lokal
:Arrangører: as Arrangører
:Sponsorer: as Sponsorer
:3-parter: as Tredje
:Admin: as Admin

Arrangører <|-- Sponsorer

(Registrere aktivitet) as (RegAktivitet)
(Påmelding) as (Påmelding)
(Opprette brukerprofil) as (Opprette)
(Opprette ny konkurranse) as (NyKonk)
(Browse konkurranser) as (Browse)
(Velge aktivitet) as (VelgeAkt)
(Se resultater) as (Resultater)
(Betale påmelding) as (Betale)

(Påmelding)<..(Betale) :Extend
(Resultater)<..(Browse) :Extend


Bruker --> (Opprette)
Bruker --> (Påmelding)
Bruker --> (Resultater)
Bruker --> (VelgeAkt)

Admin --> (NyKonk)

Lokal --> (Opprette)
Lokal --> (Påmelding)
Lokal --> (RegAktivitet)
Lokal --> (NyKonk)
Lokal --> (Resultater)

Arrangører --> (NyKonk)

@enduml
